version: 1.0.0

build:
  tools:
    python: "3.10"

sphinx:
  fail_on_warning: true

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: . 

formats:
  - pdf
  - epub