name: comb-model
dependencies:
        - python
        - tqdm
        - numpy
        - pip:
          - recommonmark
          - readthedocs-sphinx-ext
          - stochastic
          - nu
        - mock
        - pillow
        - sphinx
        - sphinx_rtd_theme